### ISSUE TITLE
required properties is not supported

### ISSUE THREAD

**Issue by hosseinmd** [hosseinmd/swagger-typescript#13]
https://github.com/hosseinmd/swagger-typescript/pull/12
Schema has a required property which specified which property of Properties is not nullable. There is confusion because every property also has a nullable property.
I solved that v 3.3.4-next1. @rodrigozoff @tbowmo

**Comment by rodrigozoff** [comment]
By default, all object properties are optional. You can specify the required properties in the required list.
In my case I use this list for this.

**Comment by tbowmo** [comment]
Haven't looked at the required property yet, but will do when I get the time (off grid for the weekend though, so will be next week before I get around to it..)

**Comment by hosseinmd** [comment]
> Haven't looked at the required property yet, but will do when I get the time (off grid for the weekend though, so will be next week before I get around to it..)

I changed @rodrigozoff PR and published to 3.3.4-next1. Check it out.

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/swagger-typescript/commits/required

**Comment by rodrigozoff** [comment]
Hi! In my fork, I did many changes, Improvements for me. 

- Use operationid over convention for the servicename.
- Replace interfaces for classes that extends DtoBase for custom implementations.
- Support to required list.
- First letter of name of documents in upper case.
- Add format, min, max, pattern, maxLength to the JDOC.

In my project, my custom implementation of DtoBase, have a method that Validate using the definition in models in OAS and return a list of invalidations. 

Please, if you considen that all chages are improvements, I make a pull request after test all.

Sorry for my English, I know is bad.

**Comment by hosseinmd** [comment]
All right, thank you, please create a PR, I think we should discuss them.

**Comment by hosseinmd** [comment]
I think a single function is so beautiful to use, a group of tags is not seemed handsome (maybe just for JavaScript developers). We chose to call it just a single function, instead of an object. for example: `postUsuario(params)` is so better than `Apis.usuario.postUsuario(params)`
So about Operationid, we added methodName to swagger.config.json to customize the name of the method,(Added in Readme).

**Comment by rodrigozoff** [comment]
I just did the pullrequest.
About 
> " for example: postUsuario(params) is so better than Apis.usuario.postUsuario(params) "

In ours  implementations:
```

import { Apis } from "../services";

const apiLugarPasajero = Apis.LugarPasajero;
const apiUsuario = Apis.Usuario;
const apiPasajero = Apis.Pasajero;
```
Then use like this 

`let response = await apiPasajero.getPasajero({ id: this.controller.IdUsuario });`

One import.

**Comment by tbowmo** [comment]
@rodrigozoff at could also be accomplished with the following

`import * as api from ". /services'`

I like the possibility to only include what's needed, and nothing else.

**Comment by hosseinmd** [comment]
Importing a single function has a benefit for webpack, it can delete another function which was never used.

**Comment by rodrigozoff** [comment]
In ours case, for now, we have 900 operations, in the future more. Finding them is slowest that using the [tag].[operationid] like sawgger ui. I will working about that (Functional Programmig maybe is the solution)

**Comment by hosseinmd** [comment]
> In ours case, for now, we have 900 operations, in the future more. Finding them is slowest that using the [tag].[operationid] like sawgger ui. I will working about that (Functional Programmig maybe is the solution)

I have another suggestion about that. We can separate methods into files based on tags.
For example: 
currently
```js
import {getAccount} from './dir/services'
```
to 
```js
import {getAccount} from './dir/account'` <-- account is tag
```
or 
```js 
import * as Account from './dir/account';
Account.getAccount();
``

**Comment by tbowmo** [comment]
@hosseinmd that sounds like an excellent plan, to split things into multiple files, based on tags.
But what if an operation has multiple tags?

**Comment by hosseinmd** [comment]
Maybe combine them together, for example tags are: ["foo","bar"] we are combining them and make a file name `fooBar.ts`, but I am not sure if the tags are stable.

**Comment by hosseinmd** [comment]
And `tags` is not required. What about services that don't have tags?

**Comment by tbowmo** [comment]
If they don't have a tag, then put them in the "unknown" bucket: services.ts?

**Comment by hosseinmd** [comment]
All right, it can be done.

**Comment by tbowmo** [comment]
Perhaps this "tags" thing is suitable to split into a new issue (since the original required property is solved)?
