### ISSUE TITLE
split services to files based on tags

### ISSUE THREAD

**Issue by hosseinmd** [hosseinmd/swagger-typescript#15]
https://github.com/hosseinmd/swagger-typescript/issues/13

We need to split the services.ts to files based on tags, because that could be a huge file.

**Comment by rodrigozoff** [comment]
Hi! I just sent a pull request, with a possible resolution of this. Please review and I await your feedback.. Thanks

**Comment by hosseinmd** [comment]
@tbowmo have a new idea for this issue
https://github.com/hosseinmd/swagger-typescript/issues/17
