### ISSUE TITLE
Split types / interfaces and methods in two files

### ISSUE THREAD

**Issue by tbowmo** [hosseinmd/swagger-typescript#17]
This is just an idea, 

Move all constants / types / interfaces to a separate file, instead of having all in the same as the api functions

**Comment by hosseinmd** [comment]
That seems good.

**Comment by hosseinmd** [comment]
Please tell me if you would like to do it.

**Comment by tbowmo** [comment]
I'll have a look at it during the coming week.

**Comment by tbowmo** [comment]
I still have it on my near-future-to-do list. But might be a couple of weeks before I come around to it, as I have a bit of time pressure on a couple of other deliveries right now.
