### ISSUE TITLE
error in generate enums with default swagger config (int)

### ISSUE THREAD

**Issue by majidbigdeli** [hosseinmd/swagger-typescript#18]
error in generate enums with default swagger config;

![Untitled](https://user-images.githubusercontent.com/26275762/99861149-845c2c80-2baa-11eb-89e1-0e6af9a17134.png)

enums generated default number then i get this error .

i fix this error  in server with enum as string but enums default are number

**Comment by hosseinmd** [comment]
Fixed in https://github.com/hosseinmd/swagger-typescript/commit/5c9ba615b034501d8d13a3d0162475f0ae9541ef .
check version 4.0.8
