### ISSUE TITLE
how about separate the axios from the project

### ISSUE THREAD

**Issue by LOWINC** [hosseinmd/swagger-typescript#22]
```js
  let requestInstant;
  export function setRequest(request) {
    requestInstant = request;
  }
```

[axiosInstance](https://github.com/hosseinmd/swagger-typescript/blob/master/files/config.tsf#L25)

**Comment by tbowmo** [comment]
I'm not sure what you could gain from this?

Currently we rely heavily on Axios functionality, to intercept calls to add authentication etc.
Also the file that you link to, is one that is meant to be edited / adjusted to your own likings, and won't be re-written when you create new swagger type definitions..

**Comment by LOWINC** [comment]
i am using fetch in my project, and i did a small [adjustment](https://github.com/LOWINC/swagger-typescript/blob/master/files/setHttpRequest.tsf) .
it makes more flexible to choose the request lib for this code generator.

**Comment by hosseinmd** [comment]
What about create an instance like axios by fetch apis? i thinck we could create something like axios instance instead of change all codes

**Comment by tbowmo** [comment]
Fetch is browser only, right? So no server side (nodejs).

I think that is still an edge case.

But you could try and create a pr for the feature.

**Comment by hosseinmd** [comment]
> Fetch is browser only, right? So no server side (nodejs).
> 
> I think that is still an edge case.
> 
> But you could try and create a pr for the feature.

I agree.
@LOWINC why you don't want to use Axios? Axios is just about 5kb but have so many feature for you. However, I think we could solve this issue just in config.ts by create a wrapper on fetch like axios.

**Comment by hosseinmd** [comment]
@LOWINC please tell us about that? Why you close issue?
