### ISSUE TITLE
Can we customize output code?

### ISSUE THREAD

**Issue by morelearn1990** [hosseinmd/swagger-typescript#27]
This is a very good project and has solved very important problems for me, thanks。

But,to accommodate local projects,I want to customize the output code.

Can you define a function parameter that outputs custom code？

**Comment by morelearn1990** [comment]
I will assemble parameters in specific implementation functions, including path parameters and query parameters.These parameters will be passed in config

**Comment by morelearn1990** [comment]
Here are the reasons why I want to do this:
In the front-end and back-end development of multi person collaboration, it often leads to generated file conflicts, and it has to take time to solve git conflicts.

I want to define the generated type into a declaration file or similar file, which is not submitted to the GIT repository，This file is only used for code prompt and type verification when writing code

**Comment by hosseinmd** [comment]
> Here are the reasons why I want to do this: In the front-end and back-end development of multi person collaboration, it often leads to generated file conflicts, and it has to take time to solve git conflicts.
> 
> I want to define the generated type into a declaration file or similar file, which is not submitted to the GIT repository，This file is only used for code prompt and type verification when writing code

We solved this issue.

You can you tags for generate service, for example
BackendDeveloper1 working on User
BackendDeveloper2 working on Auth
FrontDeveloper1 working on User
FrontDeveloper2 working on Auth

FrontDeveloper1 will connect to bakend1 server swagger and run this code `$ yarn sswag-ts User` this code will change only APIs which have User tag.
FrontDeveloper2 will connect to bakend2 server swagger and run this code `$ yarn sswag-ts Auth` this code will change only APIs which have Auth tag.

Now you have a services file which updated both User and Auth, and no conflicted

**Comment by hosseinmd** [comment]
So how you can do it.
Add this to your swagger.config.com
```
"keepJson": true,
```
This code will keep previous JSON for updating partially.

Run `$ yarn swag-ts` with your base backend, for example develop branch

Others need to pull this changes

Now Front1 will connect to backend1 and run `$ yarn sswag-ts User` and  Front2 will connect to backend2 and run `$ yarn sswag-ts Auth`

**Comment by morelearn1990** [comment]
Thank you.
