### ISSUE TITLE
Swag-ts not defined

### ISSUE THREAD

**Issue by rebzden-baracoda** [hosseinmd/swagger-typescript#30]
Hi, this package seems awesome, unfortunately I don't know how to use it ;(. Neither yarn swag-ts nor swag-ts from the scripts entry doesn't recognise swag-ts. I also tried to setup the node script (with the generate method) but it throws error `(node:32614) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined` when trying to call getParam('url') from the picture. Any help would be very much appreciated. Thanks!!! 🔥🔥🔥 
![image](https://user-images.githubusercontent.com/76430732/139958451-d0b3af3a-24f4-411e-8c5f-0bf103bf6523.png)

**Comment by hosseinmd** [comment]
What version of swagger-typescript you used?

**Comment by hosseinmd** [comment]
This code seem is old

**Comment by rebzden-baracoda** [comment]
I honestly have no idea why that happened but I had version 0.0.4...

**Comment by rebzden-baracoda** [comment]
maybe audit fix with force downgraded it but holy smokes... 🙉

**Comment by rebzden-baracoda** [comment]
I did however get this error `services Completed
types Completed
httpRequest Completed
TypeError: Cannot read property 'url' of undefined
failed`

**Comment by rebzden-baracoda** [comment]
but the types have generated, except for the config.ts file it's missing

**Comment by rebzden-baracoda** [comment]
I'll try to reinstall node_modules and I'll let you know, thanks a lot 😍

**Comment by hosseinmd** [comment]
test v5.6.3

**Comment by rebzden-baracoda** [comment]
Works fine thank you!!!
