### ISSUE TITLE
Method name incorrect if url has "-" or "*"

### ISSUE THREAD

**Issue by Ognev1990** [hosseinmd/swagger-typescript#33]
`diff --git a/src/utils.ts b/src/utils.ts
index ea243d1..666ba9b 100644
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -81,8 +81,7 @@ function getTemplate(methodName?: string, operationId?: string) {
   return methodName
     .replace(/(?:^\w|[A-Z]|\b\w)/g, function (word, index) {
       return index === 0 ? word.toLowerCase() : word.toUpperCase();
-    })
-    .replace(/[\s+\*+\-]/g, "");
+    }).replace(/[\s+\*+\-]/g, "");
 }

 const TYPES = {`

**Comment by hosseinmd** [comment]
hi dear

**Comment by hosseinmd** [comment]
What I understand is you have '-' or '*' in your URL and method name generated incorrectly
