### ISSUE TITLE
Return "data" from service functions

### ISSUE THREAD

**Issue by jrobertson-ed** [hosseinmd/swagger-typescript#35]
Is there any way to return the inner type from the service functions, see example below..

_Current_
`export const getUsers = (configOverride?: AxiosRequestConfig): Promise<SwaggerResponse<User[]>>`

_Desired_
`export const getUsers = (configOverride?: AxiosRequestConfig): Promise<User[]>`

I have setup an interceptor on my axios instance that will return the "data" property on successful response, however due to the service returning SwaggerResponse in typescript I'm still forced to do `response.data`

Thanks in advance

**Comment by hosseinmd** [comment]
open your config.ts and change this line
```ts
export interface SwaggerResponse<R> extends AxiosResponse<R> {}
```
to
```ts
export type SwaggerResponse<R> = R
```
