### ISSUE TITLE
Ignore Typescript Checks

### ISSUE THREAD

**Issue by jrobertson-ed** [hosseinmd/swagger-typescript#36]
Would it be possible to add `// @ts-nocheck` to the top of each generated file?

It looks like the typescript configuration of my project isn't compatible with the config used to generate the files as i get errors from the generated files, see below. 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/91904353/194042121-9d7a2cbe-4f27-4ad9-9247-f040e6d3e090.png">

Open to other ideas?

**Comment by hosseinmd** [comment]
Fixed v6.3.4
