### ISSUE TITLE
Please define swagger.config.json

### ISSUE THREAD

**Issue by jerwolff** [hosseinmd/swagger-typescript#37]
Running `yarn swag-ts` gives the error 
`Error: Please define swagger.config.json
    at getSwaggerConfig`

All I've done so far is add yarn to the project, create a swagger.config.json file with the provided example on the readme.

My swagger.config.json file is located at the root of the project.

**Comment by hosseinmd** [comment]
Hi this is hard to know why config not found. but to clearify problem i released a new version which loged expected path to swagger.config.json
 swagger-typescript@6.3.5
