### ISSUE TITLE
Using in a project without prettier

### ISSUE THREAD

**Issue by tbowmo** [hosseinmd/swagger-typescript#38]
It seems that the project has a dependency for prettier, even though it is not installed _by_ the project? (prettier is only listed in the dev dependencies)

**Comment by hosseinmd** [comment]
prettier is in peerDependencies, maybe we should add it to readme

**Comment by tbowmo** [comment]
Yes, probably a good idea to mention this in the readme file.. As yarn doesn't do anything with peer dependencies, it's not installed automatically by those who use that package manger..
