### ISSUE TITLE
Supertest minimal test case

### ISSUE THREAD

**Issue by clabnet** [hosseinmd/swagger-typescript#39]
It should be useful add a minimal test case for use an automated test suite (e.g. Supertest) to test the methods online.
Very useful project. Thank's

**Comment by hosseinmd** [comment]
Can you give me more information about what you need?

**Comment by clabnet** [comment]
Surely. 
I use a Vite project, Vue3 in Typescript, I would test the backend API using [Supertest](https://www.npmjs.com/package/supertest) framework and [Vitest](https://vitest.dev/).
I imagine one thing as is : 
```
  it('should post data to API Swagger service', async () => {
    const body = {
      "level": "CATALOG",
      "item": "MOTOR",
    }
    const response = await postGraphs(body);
    expect(response.statusCode).toBe(200);
  })
```
where postGraphs is your output method from a swagger definition.
Now, the result is 
```
Failed to fully serialize error: 'get onreadystatechange' called on an object that is not a valid instance of XMLHttpRequest
```
I think is need to config the Axios instance, but I don't know how to. 
Any suggestions, please ?

**Comment by hosseinmd** [comment]
What is your axios version?

**Comment by hosseinmd** [comment]
This seems to be the XmlHttpRequest issue which used by the Axios.
