### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named

### ISSUE THREAD

**Issue by jrobertson-ed** [hosseinmd/swagger-typescript#42]
Hi,

When I try to use one of the service functions I receive the following exception in the console. 

`Uncaught SyntaxError: The requested module '/src/services/gm/types.ts' does not provide an export named 'Account'`

If I go into the services.ts file and change the types import to be a `type` import, the issue goes away..

`import type {
    Account
} from './types'`

Could you change the generator to have this be a `type` import?

**Comment by hosseinmd** [comment]
I will fix it as soon as posible.

**Comment by hosseinmd** [comment]
Fixed: v6.4.0
