### ISSUE TITLE
When generateEnumAsType, integer enums are generated as string

### ISSUE THREAD

**Issue by ckarli** [hosseinmd/swagger-typescript#48]
Enum on the source is correctly typed as integer
![image](https://github.com/hosseinmd/swagger-typescript/assets/87313837/c55c96b8-eb27-4a8f-af61-6313077b4d30)

However types are generated as string therefore it breaks interfaces using types
`export type VatRatioChoices = "0" | "1" | "8" | "10" | "18" | "20";
`

**Comment by hosseinmd** [comment]
This is a bug. I will fix it.

**Comment by hosseinmd** [comment]
Released: v6.5.1
