### ISSUE TITLE
Migrating to TanStack Query v5

### ISSUE THREAD

**Issue by ckarli** [hosseinmd/swagger-typescript#49]
Any plans to implement changes in v5 of tanstack-query?

[Migration docs](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5)

**Comment by hosseinmd** [comment]
Your PR look good why you closed it.

**Comment by ckarli** [comment]
I missed type annotations at first. #51 is the correct one.

**Comment by hosseinmd** [comment]
v6.6.0
