### ISSUE TITLE
Should probably add a ts-ignore

### ISSUE THREAD

**Issue by tbowmo** [hosseinmd/swagger-typescript#8]
As typescript could complain with `Parameter 'param' implicitly has an 'any' type.` it would be a good idea to add
`//@ts-ignore` before paramSerializer
https://github.com/hosseinmd/swagger-typescript/blob/3f5c5fffe8c69e0aa59cfadec113372d6621a9b3/files/httpRequest.tsf#L6

**Comment by hosseinmd** [comment]
Done (https://github.com/hosseinmd/swagger-typescript/commit/6e5019cb3eed467fa7ac986b3e59b57874e06672)
