### ISSUE TITLE
skip parameters in path, when generating method names

### ISSUE THREAD

**Issue by tbowmo** [hosseinmd/swagger-typescript#9]
Would be great if parameter names could be skipped in (get) methods:

something like the following:

```json
{
"/nerdsite/{nerdId}/{deleted}": {
      "get": {
        "parameters": [
          {
            "name": "nerdId",
            "schema": {
              "type": "number"
            },
            "in": "path",
            "required": true
          },
          {
            "name": "deleted",
            "schema": {
              "type": "boolean"
            },
            "in": "path",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Nerdsite"
                  }
                }
              }
            },
            "description": "Array of nerdsites"
          }
        }
      }
    }
}
```

is converted to a method like:
```TypeScript
export const getNerdsiteNerdIdDeleted = async (
  nerdId: number,
  deleted?: boolean,
  configOverride?: AxiosRequestConfig
): Promise<SwaggerResponse<Nerdsite[]>> => {}
```

That is, it includes the parameters in the method name. It's a bit superfluous to have them in the method name, and would make a much cleaner service layer, if it was just named `getNerdsite`

**Comment by hosseinmd** [comment]
You are all right, but there is problem maybe some method have same name without parameters.
For example:
```js
"/nerdsite": {
      "get": {}
}
```

**Comment by hosseinmd** [comment]
So, if we remove parameters from the name we have two functions with the same name.

**Comment by hosseinmd** [comment]
This is also my concern. But I don't have any idea.

**Comment by tbowmo** [comment]
I hadn't thought about the issue with having another endpoint with a subset of the path. But will that ever be the case? Then both parameters are optional (which I later found out isn't supported by openapi yet). 

I'll probably end up refactoring my endpoint to use query parameters instead of path parameters. (it's an old api I'm upgrading, and adding openapi specs to).

**Comment by hosseinmd** [comment]
<img width="682" alt="Screen Shot 2020-10-18 at 11 23 17 PM" src="https://user-images.githubusercontent.com/45505767/96378464-f5b65300-1198-11eb-9df1-e995f735e107.png">

**Comment by tbowmo** [comment]
I rest my case, and close this issue, as it seems to be an impossible task :)

**Comment by tbowmo** [comment]
Had another read up on the specs, you could use the `operationId` property to generate the method names (if present), 

_operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API._

https://swagger.io/docs/specification/paths-and-operations/

**Comment by hosseinmd** [comment]
If we generate name with operation id. does it needed to put the Method type at the start of the name?

**Comment by hosseinmd** [comment]
So, to do it we could get a type in sswagget.config.json and users can define what method they want.
For example:
```json
{
"methodName": "{method}{controller}{operationId}{path}",
...
"methodName": "{method}{controller}{path}", // current, we decided this because it's not related to backend
...your case
"methodName": "{operationId}",
}
```

**Comment by tbowmo** [comment]
I don't think that the first will be used by anyone.. As it will produce a too complex method name..

For _my_ part, I had the idea of having a fallback solution:
1. priority use {operationId}
2. priority if "{operationId}" isn't present, then use "{method}{controller}{path}"

```
{
  "methodName": "{operationId}",
  "fallBackMethodName: "{method}{controller}{path}", // Use this, if "primary" methodName above results in an empty string.
}

**Comment by hosseinmd** [comment]
In our case, the back-end is another team, and they're changing operationId in period time. Because of that we choose the current way. Also, other users are using this module, we don't want to push them to bugs.

**Comment by hosseinmd** [comment]
I will add `methodName` soon.

**Comment by tbowmo** [comment]
then add methodName and fallBackMethodName properties to the swagger.config.json

If methodName results in an empty line, then use fallBackMethodName. (And if none of them is set, default back to the old method of `{method}{controller}{path}`)

Then you're backwards compatible.

**Comment by hosseinmd** [comment]
[done](https://github.com/hosseinmd/swagger-typescript/commit/4b28695e640c42e5d650fd45c980708d99a00abb)

**Comment by tbowmo** [comment]
Verified as working..

Thanks..
